version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: alco_pg
    environment:
      POSTGRES_DB: alco
      POSTGRES_USER: alco
      POSTGRES_PASSWORD: alco
    ports:
      - "5433:5432" # внешний 5433 -> внутр. 5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d 'dbname=alco user=alco'"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    container_name: alco_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
